name: Build and Deploy Gradle App to Azure Web App - loginpage-backend-qa

on:
  push:
    branches:
      - main

permissions:
  contents: read
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x demo-project1-loginpage/gradlew

      - name: Build with Gradle
        run: |
          cd demo-project1-loginpage
          ./gradlew clean bootJar -x test

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: demo-project1-loginpage/build/libs/loginpage-backend.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: loginpage-backend-qa
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_QA }}
          package: 'loginpage-backend.jar'

# PROD
  deploy_prod:
    runs-on: ubuntu-latest
    needs: deploy
    environment:
      name: production
      url: https://loginpage-backend-prod.azurewebsites.net

    steps:
      - name: Esperar aprobación manual
        uses: trstringer/manual-approval@v1
        with:
          approvers: VickyVaccarini
          issue-title: "Aprobación requerida para desplegar en producción"
          issue-body: "Por favor aprobar para desplegar el backend en PROD."
          secret: ${{ secrets.GITHUB_TOKEN }}

      - name: Descargar artefacto compilado
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Desplegar a Azure Web App PROD
        uses: azure/webapps-deploy@v3
        with:
          app-name: loginpage-backend-prod
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PROD }}
          package: 'loginpage-backend.jar'
